//! Protobuf error bodies for the OTLP ingest endpoint (SPEC §4.1.1).
//!
//! OTLP requires the body of every 4xx/5xx to be a protobuf `google.rpc.Status`. That message is
//! not in `opentelemetry-proto`, and the crate that ships it (`tonic-types`) pulls in tonic, which
//! this project otherwise avoids — so the one field actually needed is declared here.

use axum::http::{StatusCode, header};
use axum::response::{IntoResponse, Response};
use prost::Message;

/// `google.rpc.Status`, with only the field OTLP requires.
///
/// `code` (tag 1) and `details` (tag 3) are omitted: the spec permits it, states clients do not act
/// on `code`, and proto3 does not emit defaults anyway — so a client decoding with the full
/// definition sees `code = 0` and empty `details`.
#[derive(Clone, PartialEq, Message)]
pub struct Status {
    #[prost(string, tag = "2")]
    pub message: String,
}

pub const PROTOBUF: &str = "application/x-protobuf";

/// An ingest failure, rendered as an OTLP-conforming protobuf response.
#[derive(Debug)]
pub struct IngestError {
    pub status: StatusCode,
    pub message: String,
}

impl IngestError {
    pub fn new(status: StatusCode, message: impl Into<String>) -> Self {
        Self { status, message: message.into() }
    }

    pub fn bad_request(message: impl Into<String>) -> Self {
        Self::new(StatusCode::BAD_REQUEST, message)
    }

    pub fn unsupported_media_type(message: impl Into<String>) -> Self {
        Self::new(StatusCode::UNSUPPORTED_MEDIA_TYPE, message)
    }

    pub fn payload_too_large(message: impl Into<String>) -> Self {
        Self::new(StatusCode::PAYLOAD_TOO_LARGE, message)
    }

    /// Storage failures are retryable, so they must be 503 — OTLP's retry table marks 500 as
    /// non-retryable, which would tell the device to discard the only copy of a measurement.
    pub fn unavailable(message: impl Into<String>) -> Self {
        Self::new(StatusCode::SERVICE_UNAVAILABLE, message)
    }
}

impl IntoResponse for IngestError {
    fn into_response(self) -> Response {
        tracing::warn!(status = %self.status, message = %self.message, "ingest rejected");
        (
            self.status,
            [(header::CONTENT_TYPE, PROTOBUF)],
            Status { message: self.message }.encode_to_vec(),
        )
            .into_response()
    }
}

/// Rewrites any ingest-route error response that is not already protobuf into a `Status`.
///
/// Needed because responses generated by the framework rather than by our handler — a 405 from
/// method routing, for instance — would otherwise carry a non-protobuf body and break conformance.
pub async fn ensure_protobuf_errors(response: Response) -> Response {
    let status = response.status();
    if !status.is_client_error() && !status.is_server_error() {
        return response;
    }
    if response.headers().get(header::CONTENT_TYPE).and_then(|v| v.to_str().ok()) == Some(PROTOBUF) {
        return response;
    }

    let message = status.canonical_reason().unwrap_or("request failed").to_owned();
    tracing::warn!(%status, "rewriting non-protobuf error response for OTLP conformance");
    (status, [(header::CONTENT_TYPE, PROTOBUF)], Status { message }.encode_to_vec()).into_response()
}
