# Generic NixOS-VM test harness for the monitoring platform.
#
# The machine under test is an INPUT — this file knows nothing about how the
# machine is assembled. That is the whole point: the hardening in module.nix
# (RestrictAddressFamilies, SystemCallFilter, ProtectSystem=strict) can only be
# validated against the systemd the target actually runs, because sandbox semantics
# are version-dependent. A VM built from this repo's own pinned channel would
# validate them against a systemd nobody deploys (SPEC.md §11.1).
#
# An external repo tests the service against its OWN configuration by importing
# this file with its real host module:
#
#   import "${monitoring-platform}/nix/tests/lib.nix" {
#     inherit pkgs;
#     machineModules = [ self.nixosModules.common-desktop ];
#   }
#   # => { platform = <shared VM>; <isolated-case> = <own VM>; ... }
#
# Two execution models (a case picks one):
#   - lightweight (default): a subtest on ONE shared VM, booted once.
#   - isolated (`isolate = true`): its own VM, with optional extra `machineModules`
#     layered on the base machine (for cases that must change configuration).
{
  pkgs,
  machineModules,
  # The client group. A member can reach the socket; a non-member must not.
  clientUser ? "mp-client",
}:
let
  lib = pkgs.lib;

  # Layered onto the machine under test. The service module creates its own user
  # and group; this adds an unprivileged account IN that group plus one outside it,
  # so the socket's access control is testable rather than assumed.
  testClients =
    { config, ... }:
    {
      services.monitoring-platform.enable = true;

      users.users.${clientUser} = {
        isNormalUser = true;
        extraGroups = [ config.services.monitoring-platform.group ];
      };
      users.users.mp-outsider = {
        isNormalUser = true;
      };

      # curl for the HTTP-over-unix-socket probes, sqlite for inspecting rows
      # independently of the read API, and the package itself for mp-make-sample.
      environment.systemPackages = [
        pkgs.curl
        pkgs.sqlite
        config.services.monitoring-platform.package
      ];
    };

  # Python preamble. Exposes the paths and helpers every case uses, so a case body
  # is only its assertions.
  preamble = ''
    import json

    SOCKET = "/run/monitoring-platform/monitoring-platform.sock"
    DB = "/var/lib/monitoring-platform/measurements.db"
    CLIENT = "${clientUser}"

    machine.wait_for_unit("multi-user.target")
    # Type=notify, so `active` means migrations ran AND the socket is accepting.
    # Anything asserted after this point cannot be racing startup.
    machine.wait_for_unit("monitoring-platform.service")

    def curl_raw(args, user=CLIENT, succeed=True):
        # No --fail-with-body: for probes that inspect the status themselves via -w.
        # Run as a group member by default: the socket is only reachable through a
        # 0750 group-owned directory, so root-only probes would not prove access
        # works for the clients that matter.
        cmd = f"su - {user} -c " + repr(f"curl -sS --unix-socket {SOCKET} {args}")
        return (machine.succeed if succeed else machine.fail)(cmd)

    def curl(args, user=CLIENT, succeed=True):
        # --fail-with-body, so a 4xx/5xx is a non-zero exit and therefore a test
        # failure unless succeed=False.
        cmd = f"su - {user} -c " + repr(f"curl -sS --fail-with-body --unix-socket {SOCKET} {args}")
        return (machine.succeed if succeed else machine.fail)(cmd)

    def get_json(path, user=CLIENT):
        return json.loads(curl(f"http://localhost{path}", user=user))

    def post_protobuf(local_file, extra=""):
        return curl(
            f"-X POST -H 'Content-Type: application/x-protobuf' {extra} "
            f"--data-binary @{local_file} http://localhost/v1/logs"
        )

    def row_count():
        # Read-only, via a separate connection, so this is independent of the API.
        out = machine.succeed(f"sqlite3 'file:{DB}?mode=ro' 'select count(*) from measurement;'")
        return int(out.strip())

    def sample_batch(dest="/tmp/sample-logs.pb"):
        # Generated by a binary from the package under test, so the payload is built
        # by the same code the service parses — no hand-encoded protobuf in the test.
        machine.succeed(f"mp-make-sample {dest}")
        return dest
  '';

  # One VM test on the base machine plus any per-case modules.
  mkTest =
    {
      name,
      testScript,
      extraModules ? [ ],
    }:
    pkgs.testers.runNixOSTest {
      inherit name;
      # Don't pin nixpkgs.* read-only on the nodes, so a consumer's machineModules
      # may set nixpkgs.config / overlays without a types.unique collision.
      node.pkgsReadOnly = false;
      nodes.machine = {
        imports = machineModules ++ [ testClients ] ++ extraModules;
      };
      testScript = preamble + testScript;
    };

  # Each case is { testScript; isolate ? false; machineModules ? []; } and is
  # independent of how the machine under test was built.
  cases = {
    readiness = import ./cases/readiness.nix { inherit pkgs; };
    ingest = import ./cases/ingest.nix { inherit pkgs; };
    socket-access = import ./cases/socket-access.nix { inherit pkgs; };
    hardening = import ./cases/hardening.nix { inherit pkgs; };
    restart = import ./cases/restart.nix { inherit pkgs; };
    ordering = import ./cases/ordering.nix { inherit pkgs; };
    crash-recovery = import ./cases/crash-recovery.nix { inherit pkgs; };
  };

  isolated = lib.filterAttrs (_: c: c.isolate or false) cases;
  shared = lib.filterAttrs (_: c: !(c.isolate or false)) cases;

  # Wrap a lightweight case as an indented `with subtest(...)` block.
  subtestBlock =
    name: case:
    ''with subtest("${name}"):'' + "\n    " + builtins.replaceStrings [ "\n" ] [ "\n    " ] case.testScript;
  sharedBody = lib.concatStringsSep "\n\n" (lib.mapAttrsToList subtestBlock shared);

  isolatedTests = lib.mapAttrs (
    name: c:
    mkTest {
      name = "monitoring-platform-${name}";
      testScript = c.testScript;
      extraModules = c.machineModules or [ ];
    }
  ) isolated;
in
# `platform` is the reserved key for the shared VM running all lightweight cases as
# subtests; plus one entry per isolated case.
isolatedTests
// lib.optionalAttrs (shared != { }) {
  platform = mkTest {
    name = "monitoring-platform";
    testScript = sharedBody;
  };
}
